// Add DataTable component

import {
  flexRender,
  getCoreRowModel,
  getExpandedRowModel,
  getFilteredRowModel,
  getGroupedRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable
} from "@tanstack/react-table";
import {DataTableProps} from "../model/DataTableProps";
import {Select, SelectContent, SelectItem, SelectTrigger, SelectValue} from "@/components/ui/select";
import {Button} from "@/components/ui/button";
import {ChevronLeftIcon, ChevronRightIcon, TableIcon} from "@/components/icons";
import {PivotTableIcon} from "@/components/icons/ReportIcons";

export function DataTable<TData extends Record<string, any>>(props: DataTableProps<TData>) {
    const {
      data,
      columns,
      sorting,
      setSorting,
      columnFilters,
      setColumnFilters,
      columnVisibility,
      setColumnVisibility,
      pagination,
      setPagination,
      showRowCounts,
      showDetailRows,
      grouping,
      onGroupingChange,
      expandedRowGroups,
      setExpandedRowGroups,
      pageCount,
      totalRows,
      isLoading,
      isPivotTable = false,
      pivotColumns = [],
      pivotValues = []
    } = props;
  
    // Initialize the table with grouping support
    const table = useReactTable({
      data,
      columns,
      state: {
        sorting,
        columnFilters,
        columnVisibility,
        pagination,
        grouping,
      },
      onSortingChange: setSorting,
      onColumnFiltersChange: setColumnFilters,
      onColumnVisibilityChange: setColumnVisibility,
      onPaginationChange: setPagination,
      onGroupingChange,
      getCoreRowModel: getCoreRowModel(),
      getSortedRowModel: getSortedRowModel(),
      getFilteredRowModel: getFilteredRowModel(),
      getPaginationRowModel: getPaginationRowModel(),
      getGroupedRowModel: getGroupedRowModel(),
      getExpandedRowModel: getExpandedRowModel(),
    });

    // Helper function to identify pivot-related columns
    const isPivotColumn = (columnId: string) => {
      if (!isPivotTable) return false;
      
      // Check if this column was generated by pivoting
      // For actual implementation, this would need to match the pattern of pivot columns
      // from the SQL generation
      return pivotColumns.some(pc => columnId.includes(pc));
    };

    // Get the number of row header columns (non-pivot) and pivot columns
    const rowHeaderColumns = isPivotTable 
      ? table.getHeaderGroups()[0].headers.filter(h => !isPivotColumn(h.id))
      : [];
    
    const pivotDataColumns = isPivotTable 
      ? table.getHeaderGroups()[0].headers.filter(h => isPivotColumn(h.id))
      : [];

    // Get pivot value display names for header
    const getPivotValueNames = () => {
      if (!isPivotTable || !pivotValues || pivotValues.length === 0) return '';
      
      return pivotValues.map(pv => {
        const col = columns.find(c => c.id === pv);
        return col ? (typeof col.header === 'string' ? col.header : pv) : pv;
      }).join(', ');
    };
  
    return (
      <div className="h-full flex flex-col bg-white rounded-md shadow-sm">
        {isLoading && (
          <div className="absolute inset-0 bg-white/80 flex items-center justify-center z-10 backdrop-blur-sm rounded-md">
            <div className="animate-spin rounded-full h-10 w-10 border-4 border-slate-200 border-t-primary"></div>
          </div>
        )}

        {isPivotTable && (
          <div className="flex items-center gap-2 px-4 py-2 bg-indigo-50/50 border-b border-indigo-100">
            <PivotTableIcon className="h-4 w-4 text-indigo-500" />
            <span className="text-xs font-medium text-indigo-700">Pivot View</span>
          </div>
        )}

        <div className="flex-1 flex flex-col overflow-hidden rounded-t-md">
          <div className="overflow-auto flex-1 scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent hover:scrollbar-thumb-slate-300">
            <table className="min-w-full border-separate border-spacing-0">
              <thead className="bg-slate-50 text-slate-600 sticky top-0 z-10 shadow-sm">
                {isPivotTable && (
                  <tr className="pivot-header-row">
                    {/* Row fields section */}
                    {rowHeaderColumns.length > 0 && (
                      <th 
                        colSpan={rowHeaderColumns.length}
                        className="px-4 py-2 text-left text-xs font-semibold uppercase tracking-wider border-b border-slate-200 bg-slate-100"
                      >
                        <div className="flex items-center">
                          <span className="h-2 w-2 bg-slate-400 rounded-full mr-1.5"></span>
                          Rows
                        </div>
                      </th>
                    )}
                    
                    {/* Pivot data section - only show if we have pivot columns */}
                    {pivotDataColumns.length > 0 && (
                      <th 
                        colSpan={pivotDataColumns.length}
                        className="px-4 py-2 text-left text-xs font-semibold uppercase tracking-wider border-b border-slate-200 bg-indigo-50"
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center">
                            <span className="h-2 w-2 bg-indigo-400 rounded-full mr-1.5"></span>
                            <span className="mr-1">Pivot Data:</span>
                            <span className="text-indigo-700 font-medium">{getPivotValueNames()}</span>
                          </div>
                        </div>
                      </th>
                    )}
                  </tr>
                )}
                
                {table.getHeaderGroups().map((headerGroup) => (
                  <tr key={headerGroup.id}>
                    {headerGroup.headers.map((header) => {
                      const isPivot = isPivotTable && isPivotColumn(header.id);
                      
                      return (
                        <th 
                          key={header.id} 
                          className={`px-4 py-2.5 text-left text-xs font-medium tracking-wide whitespace-nowrap border-b border-slate-200 ${
                            isPivot 
                              ? 'bg-indigo-50 text-indigo-700 border-l border-l-indigo-100' 
                              : isPivotTable 
                                ? 'bg-slate-100/70 text-slate-700' 
                                : ''
                          }`}
                          style={{ width: header.getSize() }}
                        >
                          {header.isPlaceholder ? null : (
                            <div className="flex items-center gap-2">
                              {header.column.getCanGroup() && !isPivot && (
                                <Button
                                  onClick={header.column.getToggleGroupingHandler()}
                                  variant="ghost"
                                  size="icon"
                                  className="h-5 w-5 rounded-full"
                                >
                                  {header.column.getIsGrouped() ? 
                                    <TableIcon className="h-3.5 w-3.5 text-primary" /> : 
                                    <TableIcon className="h-3.5 w-3.5 text-slate-400" />
                                  }
                                </Button>
                              )}
                              <span>
                                {flexRender(
                                  header.column.columnDef.header,
                                  header.getContext()
                                )}
                              </span>
                              {header.column.getCanSort() && (
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={header.column.getToggleSortingHandler()}
                                  className="ml-1 p-0 h-5 hover:bg-transparent"
                                >
                                  <span className="text-slate-400">
                                    {{
                                      asc: '▲',
                                      desc: '▼',
                                    }[header.column.getIsSorted() as string] ?? '⇅'}
                                  </span>
                                </Button>
                              )}
                            </div>
                          )}
                        </th>
                      );
                    })}
                  </tr>
                ))}
              </thead>
              <tbody className="bg-white divide-y divide-slate-100 text-slate-700">
                {table?.getRowModel()?.rows.length === 0 ? (
                  <tr>
                    <td 
                      colSpan={columns.length} 
                      className="py-8 text-center text-slate-500"
                    >
                      No results found
                    </td>
                  </tr>
                ) : (
                  table?.getRowModel()?.rows.map((row, index) => (
                    <tr 
                      key={row.id} 
                      className={`${index % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'} hover:bg-blue-50/40 transition-colors duration-150`}
                    >
                      {row.getVisibleCells().map(cell => {
                        // Determine if the cell contains a number, date or currency
                        const cellValue = cell.getValue();
                        const isNumber = typeof cellValue === 'number' && !isNaN(cellValue);
                        const isCurrency = cell.column.id.includes('amount') || cell.column.id.includes('price') || cell.column.id.includes('revenue');
                        const isDate = cell.column.id.includes('date') || cell.column.id.includes('time');
                        const isPivot = isPivotTable && isPivotColumn(cell.column.id);
                        
                        // Set appropriate text alignment based on content type
                        let textAlignment = '';
                        if (isNumber || isCurrency) {
                          textAlignment = 'text-right';
                        } else if (isDate) {
                          textAlignment = 'text-left whitespace-nowrap';
                        }
                        
                        // Use different styles based on cell type
                        const cellStyle = cell.getIsGrouped()
                          ? 'bg-slate-100 font-medium text-slate-800 border-l-2 border-l-primary/60'
                          : cell.getIsAggregated()
                            ? 'bg-slate-50 font-medium text-slate-800'
                            : cell.getIsPlaceholder()
                              ? ''
                              : isPivot 
                                ? 'bg-indigo-50/30 text-indigo-900 font-medium border-l border-l-indigo-100/70'
                                : isPivotTable
                                  ? 'bg-slate-50/70'
                                  : '';
                              
                        return (
                          <td
                            key={cell.id}
                            className={`px-4 py-2 text-sm ${textAlignment} ${cellStyle} ${index === table.getRowModel().rows.length - 1 ? 'border-b border-slate-200' : ''}`}
                            style={{ width: cell.column.getSize() }}
                          >
                            {cell.getIsGrouped() ? (
                              <div className="flex items-center">
                                <Button
                                  onClick={row.getToggleExpandedHandler()}
                                  variant="ghost"
                                  size="sm"
                                  className="flex items-center -ml-2 px-2 py-0.5 rounded-md hover:bg-white/80 hover:shadow-sm text-slate-700"
                                >
                                  <ChevronRightIcon 
                                    className={`h-3.5 w-3.5 mr-1.5 transition-transform text-primary/80 ${row.getIsExpanded() ? 'rotate-90' : ''}`} 
                                  />
                                  <span className="font-medium">
                                    {flexRender(
                                      cell.column.columnDef.cell,
                                      cell.getContext()
                                    )}
                                  </span>
                                  {showRowCounts && (
                                    <span className="ml-2 text-xs text-slate-500 bg-white px-1.5 py-0.5 rounded-full border border-slate-200 shadow-sm">
                                      {row.subRows.length}
                                    </span>
                                  )}
                                </Button>
                              </div>
                            ) : cell.getIsAggregated() ? (
                              <span className="font-medium">
                                {flexRender(
                                  cell.column.columnDef.aggregatedCell ??
                                  cell.column.columnDef.cell,
                                  cell.getContext()
                                )}
                              </span>
                            ) : cell.getIsPlaceholder() ? null : (
                              flexRender(
                                cell.column.columnDef.cell,
                                cell.getContext()
                              )
                            )}
                          </td>
                        )
                      })}
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
        
        {/* Add pagination controls - ensure it's not part of the scrollable area */}
        <div className="flex items-center justify-between px-4 py-2.5 border-t border-slate-200 bg-slate-50/70 rounded-b-md">
          <div className="flex-1 text-sm text-slate-500">
            {totalRows > 0 ? (
              <>
                <span className="font-medium text-slate-700">
                  {pagination.pageIndex * pagination.pageSize + 1}-{Math.min((pagination.pageIndex + 1) * pagination.pageSize, totalRows)}
                </span>{' '}
                of{' '}
                <span className="font-medium text-slate-700">{totalRows}</span>{' '}
                results
              </>
            ) : (
              'No results'
            )}
          </div>
          <div className="flex items-center space-x-6">
            <div className="flex items-center space-x-2">
              <p className="text-xs text-slate-500">Rows per page</p>
              <Select
                value={`${pagination.pageSize}`}
                onValueChange={(value) => {
                  setPagination({ pageIndex: 0, pageSize: Number(value) });
                }}
              >
                <SelectTrigger className="h-7 w-[65px] text-xs bg-white border-slate-200">
                  <SelectValue placeholder={pagination.pageSize} />
                </SelectTrigger>
                <SelectContent side="top">
                  {[10, 20, 30, 40, 50].map((pageSize) => (
                    <SelectItem key={pageSize} value={`${pageSize}`} className="text-xs">
                      {pageSize}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="flex items-center space-x-1.5">
              <Button
                variant="outline"
                size="sm"
                onClick={() => table.previousPage()}
                disabled={!table.getCanPreviousPage()}
                className="h-7 w-7 p-0 flex items-center justify-center bg-white border-slate-200 text-slate-600 rounded-md"
              >
                <ChevronLeftIcon className="h-3.5 w-3.5" />
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => table.nextPage()}
                disabled={!table.getCanNextPage()}
                className="h-7 w-7 p-0 flex items-center justify-center bg-white border-slate-200 text-slate-600 rounded-md"
              >
                <ChevronRightIcon className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }